<img src="/img/chara_retina/chara_c014/chara_c014_a_001.png" id="sit_none_a_1" class="sit none a">
<img src="/img/chara_retina/chara_c014/chara_c014_n_001.png" id="sit_none_n_1" class="sit none n">
<img src="/img/chara_retina/chara_c014/chara_c014_t_001.png" id="sit_none_t_1" class="sit none t" style="display:inline;">
<img src="/img/chara_retina/chara_c016/chara_c016_a_001.png" id="sit_blinking_a_1" class="sit blinking a">
<img src="/img/chara_retina/chara_c016/chara_c016_a_002.png" id="sit_blinking_a_2" class="sit blinking a">
<img src="/img/chara_retina/chara_c016/chara_c016_n_001.png" id="sit_blinking_n_1" class="sit blinking n">
<img src="/img/chara_retina/chara_c016/chara_c016_n_002.png" id="sit_blinking_n_2" class="sit blinking n">
<img src="/img/chara_retina/chara_c016/chara_c016_t_001.png" id="sit_blinking_t_1" class="sit blinking t">
<img src="/img/chara_retina/chara_c016/chara_c016_t_002.png" id="sit_blinking_t_2" class="sit blinking t">
<img src="/img/chara_retina/chara_c017/chara_c017_a_001.png" id="sit_smiling_a_1" class="sit smiling a">
<img src="/img/chara_retina/chara_c017/chara_c017_a_002.png" id="sit_smiling_a_2" class="sit smiling a">
<img src="/img/chara_retina/chara_c017/chara_c017_a_003.png" id="sit_smiling_a_3" class="sit smiling a">
<img src="/img/chara_retina/chara_c017/chara_c017_a_004.png" id="sit_smiling_a_4" class="sit smiling a">
<img src="/img/chara_retina/chara_c017/chara_c017_a_005.png" id="sit_smiling_a_5" class="sit smiling a">
<img src="/img/chara_retina/chara_c017/chara_c017_a_006.png" id="sit_smiling_a_6" class="sit smiling a">
<img src="/img/chara_retina/chara_c017/chara_c017_a_007.png" id="sit_smiling_a_7" class="sit smiling a">
<img src="/img/chara_retina/chara_c017/chara_c017_a_008.png" id="sit_smiling_a_8" class="sit smiling a">
<img src="/img/chara_retina/chara_c017/chara_c017_a_009.png" id="sit_smiling_a_9" class="sit smiling a">
<img src="/img/chara_retina/chara_c017/chara_c017_a_010.png" id="sit_smiling_a_10" class="sit smiling a">
<img src="/img/chara_retina/chara_c017/chara_c017_n_001.png" id="sit_smiling_n_1" class="sit smiling n">
<img src="/img/chara_retina/chara_c017/chara_c017_n_002.png" id="sit_smiling_n_2" class="sit smiling n">
<img src="/img/chara_retina/chara_c017/chara_c017_n_003.png" id="sit_smiling_n_3" class="sit smiling n">
<img src="/img/chara_retina/chara_c017/chara_c017_n_004.png" id="sit_smiling_n_4" class="sit smiling n">
<img src="/img/chara_retina/chara_c017/chara_c017_n_005.png" id="sit_smiling_n_5" class="sit smiling n">
<img src="/img/chara_retina/chara_c017/chara_c017_n_006.png" id="sit_smiling_n_6" class="sit smiling n">
<img src="/img/chara_retina/chara_c017/chara_c017_n_007.png" id="sit_smiling_n_7" class="sit smiling n">
<img src="/img/chara_retina/chara_c017/chara_c017_n_008.png" id="sit_smiling_n_8" class="sit smiling n">
<img src="/img/chara_retina/chara_c017/chara_c017_n_009.png" id="sit_smiling_n_9" class="sit smiling n">
<img src="/img/chara_retina/chara_c017/chara_c017_n_010.png" id="sit_smiling_n_10" class="sit smiling n">
<img src="/img/chara_retina/chara_c017/chara_c017_t_001.png" id="sit_smiling_t_1" class="sit smiling t">
<img src="/img/chara_retina/chara_c017/chara_c017_t_002.png" id="sit_smiling_t_2" class="sit smiling t">
<img src="/img/chara_retina/chara_c017/chara_c017_t_003.png" id="sit_smiling_t_3" class="sit smiling t">
<img src="/img/chara_retina/chara_c017/chara_c017_t_004.png" id="sit_smiling_t_4" class="sit smiling t">
<img src="/img/chara_retina/chara_c017/chara_c017_t_005.png" id="sit_smiling_t_5" class="sit smiling t">
<img src="/img/chara_retina/chara_c017/chara_c017_t_006.png" id="sit_smiling_t_6" class="sit smiling t">
<img src="/img/chara_retina/chara_c017/chara_c017_t_007.png" id="sit_smiling_t_7" class="sit smiling t">
<img src="/img/chara_retina/chara_c017/chara_c017_t_008.png" id="sit_smiling_t_8" class="sit smiling t">
<img src="/img/chara_retina/chara_c017/chara_c017_t_009.png" id="sit_smiling_t_9" class="sit smiling t">
<img src="/img/chara_retina/chara_c017/chara_c017_t_010.png" id="sit_smiling_t_10" class="sit smiling t">
<img src="/img/chara_retina/chara_c019/chara_c019_a_001.png" id="sit_sadly_a_1" class="sit sadly a">
<img src="/img/chara_retina/chara_c019/chara_c019_a_002.png" id="sit_sadly_a_2" class="sit sadly a">
<img src="/img/chara_retina/chara_c019/chara_c019_a_003.png" id="sit_sadly_a_3" class="sit sadly a">
<img src="/img/chara_retina/chara_c019/chara_c019_a_004.png" id="sit_sadly_a_4" class="sit sadly a">
<img src="/img/chara_retina/chara_c019/chara_c019_a_005.png" id="sit_sadly_a_5" class="sit sadly a">
<img src="/img/chara_retina/chara_c019/chara_c019_a_006.png" id="sit_sadly_a_6" class="sit sadly a">
<img src="/img/chara_retina/chara_c019/chara_c019_a_007.png" id="sit_sadly_a_7" class="sit sadly a">
<img src="/img/chara_retina/chara_c019/chara_c019_a_008.png" id="sit_sadly_a_8" class="sit sadly a">
<img src="/img/chara_retina/chara_c019/chara_c019_a_009.png" id="sit_sadly_a_9" class="sit sadly a">
<img src="/img/chara_retina/chara_c019/chara_c019_a_010.png" id="sit_sadly_a_10" class="sit sadly a">
<img src="/img/chara_retina/chara_c019/chara_c019_n_001.png" id="sit_sadly_n_1" class="sit sadly n">
<img src="/img/chara_retina/chara_c019/chara_c019_n_002.png" id="sit_sadly_n_2" class="sit sadly n">
<img src="/img/chara_retina/chara_c019/chara_c019_n_003.png" id="sit_sadly_n_3" class="sit sadly n">
<img src="/img/chara_retina/chara_c019/chara_c019_n_004.png" id="sit_sadly_n_4" class="sit sadly n">
<img src="/img/chara_retina/chara_c019/chara_c019_n_005.png" id="sit_sadly_n_5" class="sit sadly n">
<img src="/img/chara_retina/chara_c019/chara_c019_n_006.png" id="sit_sadly_n_6" class="sit sadly n">
<img src="/img/chara_retina/chara_c019/chara_c019_n_007.png" id="sit_sadly_n_7" class="sit sadly n">
<img src="/img/chara_retina/chara_c019/chara_c019_n_008.png" id="sit_sadly_n_8" class="sit sadly n">
<img src="/img/chara_retina/chara_c019/chara_c019_n_009.png" id="sit_sadly_n_9" class="sit sadly n">
<img src="/img/chara_retina/chara_c019/chara_c019_n_010.png" id="sit_sadly_n_10" class="sit sadly n">
<img src="/img/chara_retina/chara_c019/chara_c019_t_001.png" id="sit_sadly_t_1" class="sit sadly t">
<img src="/img/chara_retina/chara_c019/chara_c019_t_002.png" id="sit_sadly_t_2" class="sit sadly t">
<img src="/img/chara_retina/chara_c019/chara_c019_t_003.png" id="sit_sadly_t_3" class="sit sadly t">
<img src="/img/chara_retina/chara_c019/chara_c019_t_004.png" id="sit_sadly_t_4" class="sit sadly t">
<img src="/img/chara_retina/chara_c019/chara_c019_t_005.png" id="sit_sadly_t_5" class="sit sadly t">
<img src="/img/chara_retina/chara_c019/chara_c019_t_006.png" id="sit_sadly_t_6" class="sit sadly t">
<img src="/img/chara_retina/chara_c019/chara_c019_t_007.png" id="sit_sadly_t_7" class="sit sadly t">
<img src="/img/chara_retina/chara_c019/chara_c019_t_008.png" id="sit_sadly_t_8" class="sit sadly t">
<img src="/img/chara_retina/chara_c019/chara_c019_t_009.png" id="sit_sadly_t_9" class="sit sadly t">
<img src="/img/chara_retina/chara_c019/chara_c019_t_010.png" id="sit_sadly_t_10" class="sit sadly t">
<img src="/img/chara_retina/chara_c020/chara_c020_a_001.png" id="sit_blushed_a_1" class="sit blushed a">
<img src="/img/chara_retina/chara_c020/chara_c020_a_002.png" id="sit_blushed_a_2" class="sit blushed a">
<img src="/img/chara_retina/chara_c020/chara_c020_a_003.png" id="sit_blushed_a_3" class="sit blushed a">
<img src="/img/chara_retina/chara_c020/chara_c020_a_004.png" id="sit_blushed_a_4" class="sit blushed a">
<img src="/img/chara_retina/chara_c020/chara_c020_a_005.png" id="sit_blushed_a_5" class="sit blushed a">
<img src="/img/chara_retina/chara_c020/chara_c020_a_006.png" id="sit_blushed_a_6" class="sit blushed a">
<img src="/img/chara_retina/chara_c020/chara_c020_a_007.png" id="sit_blushed_a_7" class="sit blushed a">
<img src="/img/chara_retina/chara_c020/chara_c020_a_008.png" id="sit_blushed_a_8" class="sit blushed a">
<img src="/img/chara_retina/chara_c020/chara_c020_a_009.png" id="sit_blushed_a_9" class="sit blushed a">
<img src="/img/chara_retina/chara_c020/chara_c020_a_010.png" id="sit_blushed_a_10" class="sit blushed a">
<img src="/img/chara_retina/chara_c020/chara_c020_n_001.png" id="sit_blushed_n_1" class="sit blushed n">
<img src="/img/chara_retina/chara_c020/chara_c020_n_002.png" id="sit_blushed_n_2" class="sit blushed n">
<img src="/img/chara_retina/chara_c020/chara_c020_n_003.png" id="sit_blushed_n_3" class="sit blushed n">
<img src="/img/chara_retina/chara_c020/chara_c020_n_004.png" id="sit_blushed_n_4" class="sit blushed n">
<img src="/img/chara_retina/chara_c020/chara_c020_n_005.png" id="sit_blushed_n_5" class="sit blushed n">
<img src="/img/chara_retina/chara_c020/chara_c020_n_006.png" id="sit_blushed_n_6" class="sit blushed n">
<img src="/img/chara_retina/chara_c020/chara_c020_n_007.png" id="sit_blushed_n_7" class="sit blushed n">
<img src="/img/chara_retina/chara_c020/chara_c020_n_008.png" id="sit_blushed_n_8" class="sit blushed n">
<img src="/img/chara_retina/chara_c020/chara_c020_n_009.png" id="sit_blushed_n_9" class="sit blushed n">
<img src="/img/chara_retina/chara_c020/chara_c020_n_010.png" id="sit_blushed_n_10" class="sit blushed n">
<img src="/img/chara_retina/chara_c020/chara_c020_t_001.png" id="sit_blushed_t_1" class="sit blushed t">
<img src="/img/chara_retina/chara_c020/chara_c020_t_002.png" id="sit_blushed_t_2" class="sit blushed t">
<img src="/img/chara_retina/chara_c020/chara_c020_t_003.png" id="sit_blushed_t_3" class="sit blushed t">
<img src="/img/chara_retina/chara_c020/chara_c020_t_004.png" id="sit_blushed_t_4" class="sit blushed t">
<img src="/img/chara_retina/chara_c020/chara_c020_t_005.png" id="sit_blushed_t_5" class="sit blushed t">
<img src="/img/chara_retina/chara_c020/chara_c020_t_006.png" id="sit_blushed_t_6" class="sit blushed t">
<img src="/img/chara_retina/chara_c020/chara_c020_t_007.png" id="sit_blushed_t_7" class="sit blushed t">
<img src="/img/chara_retina/chara_c020/chara_c020_t_008.png" id="sit_blushed_t_8" class="sit blushed t">
<img src="/img/chara_retina/chara_c020/chara_c020_t_009.png" id="sit_blushed_t_9" class="sit blushed t">
<img src="/img/chara_retina/chara_c020/chara_c020_t_010.png" id="sit_blushed_t_10" class="sit blushed t">
<img src="/img/chara_retina/chara_c021/chara_c021_a_001.png" id="sit_blushed2_a_1" class="sit blushed2 a">
<img src="/img/chara_retina/chara_c021/chara_c021_a_002.png" id="sit_blushed2_a_2" class="sit blushed2 a">
<img src="/img/chara_retina/chara_c021/chara_c021_n_001.png" id="sit_blushed2_n_1" class="sit blushed2 n">
<img src="/img/chara_retina/chara_c021/chara_c021_n_002.png" id="sit_blushed2_n_2" class="sit blushed2 n">
<img src="/img/chara_retina/chara_c021/chara_c021_t_001.png" id="sit_blushed2_t_1" class="sit blushed2 t">
<img src="/img/chara_retina/chara_c021/chara_c021_t_002.png" id="sit_blushed2_t_2" class="sit blushed2 t">
<img src="/img/chara_retina/chara_c022/chara_c022_a_001.png" id="sit_scary_a_1" class="sit scary a">
<img src="/img/chara_retina/chara_c022/chara_c022_a_002.png" id="sit_scary_a_2" class="sit scary a">
<img src="/img/chara_retina/chara_c022/chara_c022_a_003.png" id="sit_scary_a_3" class="sit scary a">
<img src="/img/chara_retina/chara_c022/chara_c022_a_004.png" id="sit_scary_a_4" class="sit scary a">
<img src="/img/chara_retina/chara_c022/chara_c022_a_005.png" id="sit_scary_a_5" class="sit scary a">
<img src="/img/chara_retina/chara_c022/chara_c022_a_006.png" id="sit_scary_a_6" class="sit scary a">
<img src="/img/chara_retina/chara_c022/chara_c022_a_007.png" id="sit_scary_a_7" class="sit scary a">
<img src="/img/chara_retina/chara_c022/chara_c022_a_008.png" id="sit_scary_a_8" class="sit scary a">
<img src="/img/chara_retina/chara_c022/chara_c022_a_009.png" id="sit_scary_a_9" class="sit scary a">
<img src="/img/chara_retina/chara_c022/chara_c022_a_010.png" id="sit_scary_a_10" class="sit scary a">
<img src="/img/chara_retina/chara_c022/chara_c022_n_001.png" id="sit_scary_n_1" class="sit scary n">
<img src="/img/chara_retina/chara_c022/chara_c022_n_002.png" id="sit_scary_n_2" class="sit scary n">
<img src="/img/chara_retina/chara_c022/chara_c022_n_003.png" id="sit_scary_n_3" class="sit scary n">
<img src="/img/chara_retina/chara_c022/chara_c022_n_004.png" id="sit_scary_n_4" class="sit scary n">
<img src="/img/chara_retina/chara_c022/chara_c022_n_005.png" id="sit_scary_n_5" class="sit scary n">
<img src="/img/chara_retina/chara_c022/chara_c022_n_006.png" id="sit_scary_n_6" class="sit scary n">
<img src="/img/chara_retina/chara_c022/chara_c022_n_007.png" id="sit_scary_n_7" class="sit scary n">
<img src="/img/chara_retina/chara_c022/chara_c022_n_008.png" id="sit_scary_n_8" class="sit scary n">
<img src="/img/chara_retina/chara_c022/chara_c022_n_009.png" id="sit_scary_n_9" class="sit scary n">
<img src="/img/chara_retina/chara_c022/chara_c022_n_010.png" id="sit_scary_n_10" class="sit scary n">
<img src="/img/chara_retina/chara_c022/chara_c022_t_001.png" id="sit_scary_t_1" class="sit scary t">
<img src="/img/chara_retina/chara_c022/chara_c022_t_002.png" id="sit_scary_t_2" class="sit scary t">
<img src="/img/chara_retina/chara_c022/chara_c022_t_003.png" id="sit_scary_t_3" class="sit scary t">
<img src="/img/chara_retina/chara_c022/chara_c022_t_004.png" id="sit_scary_t_4" class="sit scary t">
<img src="/img/chara_retina/chara_c022/chara_c022_t_005.png" id="sit_scary_t_5" class="sit scary t">
<img src="/img/chara_retina/chara_c022/chara_c022_t_006.png" id="sit_scary_t_6" class="sit scary t">
<img src="/img/chara_retina/chara_c022/chara_c022_t_007.png" id="sit_scary_t_7" class="sit scary t">
<img src="/img/chara_retina/chara_c022/chara_c022_t_008.png" id="sit_scary_t_8" class="sit scary t">
<img src="/img/chara_retina/chara_c022/chara_c022_t_009.png" id="sit_scary_t_9" class="sit scary t">
<img src="/img/chara_retina/chara_c022/chara_c022_t_010.png" id="sit_scary_t_10" class="sit scary t">
<img src="/img/chara_retina/chara_c023/chara_c023_a_001.png" id="read_to_read_a_1" class="read to_read a">
<img src="/img/chara_retina/chara_c023/chara_c023_a_002.png" id="read_to_read_a_2" class="read to_read a">
<img src="/img/chara_retina/chara_c023/chara_c023_a_003.png" id="read_to_read_a_3" class="read to_read a">
<img src="/img/chara_retina/chara_c023/chara_c023_a_004.png" id="read_to_read_a_4" class="read to_read a">
<img src="/img/chara_retina/chara_c023/chara_c023_a_005.png" id="read_to_read_a_5" class="read to_read a">
<img src="/img/chara_retina/chara_c023/chara_c023_n_001.png" id="read_to_read_n_1" class="read to_read n">
<img src="/img/chara_retina/chara_c023/chara_c023_n_002.png" id="read_to_read_n_2" class="read to_read n">
<img src="/img/chara_retina/chara_c023/chara_c023_n_003.png" id="read_to_read_n_3" class="read to_read n">
<img src="/img/chara_retina/chara_c023/chara_c023_n_004.png" id="read_to_read_n_4" class="read to_read n">
<img src="/img/chara_retina/chara_c023/chara_c023_n_005.png" id="read_to_read_n_5" class="read to_read n">
<img src="/img/chara_retina/chara_c023/chara_c023_t_001.png" id="read_to_read_t_1" class="read to_read t">
<img src="/img/chara_retina/chara_c023/chara_c023_t_002.png" id="read_to_read_t_2" class="read to_read t">
<img src="/img/chara_retina/chara_c023/chara_c023_t_003.png" id="read_to_read_t_3" class="read to_read t">
<img src="/img/chara_retina/chara_c023/chara_c023_t_004.png" id="read_to_read_t_4" class="read to_read t">
<img src="/img/chara_retina/chara_c023/chara_c023_t_005.png" id="read_to_read_t_5" class="read to_read t">
<img src="/img/chara_retina/chara_c024/chara_c024_a_001.png" id="read_none_a_1" class="read none a">
<img src="/img/chara_retina/chara_c024/chara_c024_n_001.png" id="read_none_n_1" class="read none n">
<img src="/img/chara_retina/chara_c024/chara_c024_t_001.png" id="read_none_t_1" class="read none t">
<img src="/img/chara_retina/chara_c025/chara_c025_a_001.png" id="read_to_sit_a_1" class="read to_sit a">
<img src="/img/chara_retina/chara_c025/chara_c025_a_002.png" id="read_to_sit_a_2" class="read to_sit a">
<img src="/img/chara_retina/chara_c025/chara_c025_a_003.png" id="read_to_sit_a_3" class="read to_sit a">
<img src="/img/chara_retina/chara_c025/chara_c025_a_004.png" id="read_to_sit_a_4" class="read to_sit a">
<img src="/img/chara_retina/chara_c025/chara_c025_a_005.png" id="read_to_sit_a_5" class="read to_sit a">
<img src="/img/chara_retina/chara_c025/chara_c025_n_001.png" id="read_to_sit_n_1" class="read to_sit n">
<img src="/img/chara_retina/chara_c025/chara_c025_n_002.png" id="read_to_sit_n_2" class="read to_sit n">
<img src="/img/chara_retina/chara_c025/chara_c025_n_003.png" id="read_to_sit_n_3" class="read to_sit n">
<img src="/img/chara_retina/chara_c025/chara_c025_n_004.png" id="read_to_sit_n_4" class="read to_sit n">
<img src="/img/chara_retina/chara_c025/chara_c025_n_005.png" id="read_to_sit_n_5" class="read to_sit n">
<img src="/img/chara_retina/chara_c025/chara_c025_t_001.png" id="read_to_sit_t_1" class="read to_sit t">
<img src="/img/chara_retina/chara_c025/chara_c025_t_002.png" id="read_to_sit_t_2" class="read to_sit t">
<img src="/img/chara_retina/chara_c025/chara_c025_t_003.png" id="read_to_sit_t_3" class="read to_sit t">
<img src="/img/chara_retina/chara_c025/chara_c025_t_004.png" id="read_to_sit_t_4" class="read to_sit t">
<img src="/img/chara_retina/chara_c025/chara_c025_t_005.png" id="read_to_sit_t_5" class="read to_sit t">
<img src="/img/chara_retina/chara_c026/chara_c026_a_001.png" id="read_blinking_a_1" class="read blinking a">
<img src="/img/chara_retina/chara_c026/chara_c026_a_002.png" id="read_blinking_a_2" class="read blinking a">
<img src="/img/chara_retina/chara_c026/chara_c026_n_001.png" id="read_blinking_n_1" class="read blinking n">
<img src="/img/chara_retina/chara_c026/chara_c026_n_002.png" id="read_blinking_n_2" class="read blinking n">
<img src="/img/chara_retina/chara_c026/chara_c026_t_001.png" id="read_blinking_t_1" class="read blinking t">
<img src="/img/chara_retina/chara_c026/chara_c026_t_002.png" id="read_blinking_t_2" class="read blinking t">
<img src="/img/chara_retina/chara_c027/chara_c027_a_001.png" id="read_paging_a_1" class="read paging a">
<img src="/img/chara_retina/chara_c027/chara_c027_a_002.png" id="read_paging_a_2" class="read paging a">
<img src="/img/chara_retina/chara_c027/chara_c027_a_003.png" id="read_paging_a_3" class="read paging a">
<img src="/img/chara_retina/chara_c027/chara_c027_a_004.png" id="read_paging_a_4" class="read paging a">
<img src="/img/chara_retina/chara_c027/chara_c027_a_005.png" id="read_paging_a_5" class="read paging a">
<img src="/img/chara_retina/chara_c027/chara_c027_a_006.png" id="read_paging_a_6" class="read paging a">
<img src="/img/chara_retina/chara_c027/chara_c027_a_007.png" id="read_paging_a_7" class="read paging a">
<img src="/img/chara_retina/chara_c027/chara_c027_a_008.png" id="read_paging_a_8" class="read paging a">
<img src="/img/chara_retina/chara_c027/chara_c027_a_009.png" id="read_paging_a_9" class="read paging a">
<img src="/img/chara_retina/chara_c027/chara_c027_a_010.png" id="read_paging_a_10" class="read paging a">
<img src="/img/chara_retina/chara_c027/chara_c027_a_011.png" id="read_paging_a_11" class="read paging a">
<img src="/img/chara_retina/chara_c027/chara_c027_a_012.png" id="read_paging_a_12" class="read paging a">
<img src="/img/chara_retina/chara_c027/chara_c027_a_013.png" id="read_paging_a_13" class="read paging a">
<img src="/img/chara_retina/chara_c027/chara_c027_a_014.png" id="read_paging_a_14" class="read paging a">
<img src="/img/chara_retina/chara_c027/chara_c027_n_001.png" id="read_paging_n_1" class="read paging n">
<img src="/img/chara_retina/chara_c027/chara_c027_n_002.png" id="read_paging_n_2" class="read paging n">
<img src="/img/chara_retina/chara_c027/chara_c027_n_003.png" id="read_paging_n_3" class="read paging n">
<img src="/img/chara_retina/chara_c027/chara_c027_n_004.png" id="read_paging_n_4" class="read paging n">
<img src="/img/chara_retina/chara_c027/chara_c027_n_005.png" id="read_paging_n_5" class="read paging n">
<img src="/img/chara_retina/chara_c027/chara_c027_n_006.png" id="read_paging_n_6" class="read paging n">
<img src="/img/chara_retina/chara_c027/chara_c027_n_007.png" id="read_paging_n_7" class="read paging n">
<img src="/img/chara_retina/chara_c027/chara_c027_n_008.png" id="read_paging_n_8" class="read paging n">
<img src="/img/chara_retina/chara_c027/chara_c027_n_009.png" id="read_paging_n_9" class="read paging n">
<img src="/img/chara_retina/chara_c027/chara_c027_n_010.png" id="read_paging_n_10" class="read paging n">
<img src="/img/chara_retina/chara_c027/chara_c027_n_011.png" id="read_paging_n_11" class="read paging n">
<img src="/img/chara_retina/chara_c027/chara_c027_n_012.png" id="read_paging_n_12" class="read paging n">
<img src="/img/chara_retina/chara_c027/chara_c027_n_013.png" id="read_paging_n_13" class="read paging n">
<img src="/img/chara_retina/chara_c027/chara_c027_n_014.png" id="read_paging_n_14" class="read paging n">
<img src="/img/chara_retina/chara_c027/chara_c027_t_001.png" id="read_paging_t_1" class="read paging t">
<img src="/img/chara_retina/chara_c027/chara_c027_t_002.png" id="read_paging_t_2" class="read paging t">
<img src="/img/chara_retina/chara_c027/chara_c027_t_003.png" id="read_paging_t_3" class="read paging t">
<img src="/img/chara_retina/chara_c027/chara_c027_t_004.png" id="read_paging_t_4" class="read paging t">
<img src="/img/chara_retina/chara_c027/chara_c027_t_005.png" id="read_paging_t_5" class="read paging t">
<img src="/img/chara_retina/chara_c027/chara_c027_t_006.png" id="read_paging_t_6" class="read paging t">
<img src="/img/chara_retina/chara_c027/chara_c027_t_007.png" id="read_paging_t_7" class="read paging t">
<img src="/img/chara_retina/chara_c027/chara_c027_t_008.png" id="read_paging_t_8" class="read paging t">
<img src="/img/chara_retina/chara_c027/chara_c027_t_009.png" id="read_paging_t_9" class="read paging t">
<img src="/img/chara_retina/chara_c027/chara_c027_t_010.png" id="read_paging_t_10" class="read paging t">
<img src="/img/chara_retina/chara_c027/chara_c027_t_011.png" id="read_paging_t_11" class="read paging t">
<img src="/img/chara_retina/chara_c027/chara_c027_t_012.png" id="read_paging_t_12" class="read paging t">
<img src="/img/chara_retina/chara_c027/chara_c027_t_013.png" id="read_paging_t_13" class="read paging t">
<img src="/img/chara_retina/chara_c027/chara_c027_t_014.png" id="read_paging_t_14" class="read paging t">